language: objective-c
osx_image: xcode8.1
before_install:
  - brew update
  - brew install carthage
script: xctool -project YTVimeoExtractor.xcodeproj -scheme YTVimeoExtractor build test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - carthage build --no-skip-current
  - carthage archive YTVimeoExtractor
skip_cleanup: true
on:
  repo: repo/repo
  tags: true
